[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"


[build]
  base = "personality_score"
  command = "flutter build web"
  publish = "personality_score/build/web --release"

